name: Kedro CI

on:
  push:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
          # Check if CUDA is available and install the appropriate dependencies
          if python -c "import torch; print(torch.cuda.is_available())" | grep -q 'True'; then
            pip install .[cuda]
          else
            pip install .[cpu]
          fi

      - name: Install additional testing dependencies
        run: |
          pip install pytest-cov  # Ensure pytest-cov is installed

      - name: Run tests
        run: |
          pytest --cov=src/misars_pipeline_kedro --cov-report term-missing tests/